feat(be): fix analytics endpoint
RBND-studio/flows-cloud pull request #133
Opened 2024-03-02 09:30 UTC by pesickadavid

2024-03-02 13:43 UTC, VojtechVidra requested changes

2024-03-02 13:43 UTC, VojtechVidra commented on apps/app/src/app/(auth)/reset-password/new/reset-password-new-form.tsx
> +export const ResetPasswordNewForm = (): JSX.Element => {
This page seems to me like something's missing 😄

2024-03-02 13:43 UTC, VojtechVidra commented on apps/app/src/app/(auth)/login/login-form.tsx
> +        <Text align="center" color="muted">
Also remove the comment at the top of this file 🙂

2024-03-02 13:47 UTC, VojtechVidra commented on apps/app/src/app/(auth)/reset-password/success/reset-password-success.tsx
> +          We&apos;ve sent a verification link.
I think better would be to say something like: "We've sent you a link to `...` where you can create new password."

2024-03-02 13:49 UTC, VojtechVidra commented on apps/app/src/app/(auth)/reset-password/new/reset-password-new-form.tsx
> +  supabase.auth.onAuthStateChange((event) => {
This shouldn't be needed, since we have similar logic in `apps/app/src/app/(auth)/layout.tsx`. Or this will redirect the user when they set a new password?

2024-03-02 14:23 UTC, pesickadavid commented on apps/app/src/app/(auth)/reset-password/new/reset-password-new-form.tsx
> +export const ResetPasswordNewForm = (): JSX.Element => {
Missing a lot 😄

2024-03-02 14:29 UTC, pesickadavid commented on apps/app/src/app/(auth)/reset-password/success/reset-password-success.tsx
> +          We&apos;ve sent a verification link.
That is a wording Taken from Atmos 😄 But we can you the one you're suggesting.

2024-03-02 14:30 UTC, pesickadavid commented on apps/app/src/app/(auth)/reset-password/new/reset-password-new-form.tsx
> +  supabase.auth.onAuthStateChange((event) => {
Not finished yet. Supabase docs are kinda confusing. Need this PR to be merged before i can implement the rest.

2024-03-03 20:10 UTC, pesickadavid commented on apps/app/src/app/(auth)/login/login-form.tsx
> +        <Text align="center" color="muted">
Removed

2024-03-03 20:10 UTC, pesickadavid commented on apps/app/src/app/(auth)/reset-password/success/reset-password-success.tsx
> +          We&apos;ve sent a verification link.
Updated

2024-03-03 20:51 UTC, pesickadavid commented on apps/app/src/app/(auth)/reset-password/new/reset-password-new-form.tsx
> +export const ResetPasswordNewForm = (): JSX.Element => {
Updated

2024-03-03 20:52 UTC, pesickadavid commented on apps/app/src/app/(auth)/reset-password/new/reset-password-new-form.tsx
> +  supabase.auth.onAuthStateChange((event) => {
Removed this and used check in layout.

2024-03-04 06:51 UTC, pesickadavid commented on apps/app/src/lib/constants.ts
> +export const STAGING = process.env.NEXT_PUBLIC_ENV === "staging";
Forgot to delete, used in the pre-OTP version of auth.

2024-03-04 06:58 UTC, pesickadavid commented on apps/app/src/app/(auth)/login/login-form.tsx
> +      captchaRef.current?.reset();
I've had to reload the page to be able to enter the correct one. Wihtout this it just failed over and over. Because it did not expire but rather got used. Gonna try with the `onExpire` hook
![image](https://github.com/RBND-studio/flows-cloud/assets/61206880/2cb417e4-5896-4299-9a7e-a82e77103690)

2024-03-04 07:03 UTC, pesickadavid commented on apps/app/src/app/(auth)/login/login-form.tsx
> +      captchaRef.current?.reset();
The error is comming from Auth, so Turnstile has no idea that its token has been used, we need to reset it manually

2024-03-04 07:09 UTC, pesickadavid commented on apps/app/src/app/(reset-password)/reset-password/new/layout.tsx
> +  if (!auth) return <Text>Loading...</Text>;
Aaah, thought that it would update itself when it loads the user.

2024-03-04 07:16 UTC, pesickadavid commented on apps/app/src/app/(reset-password)/reset-password/new/layout.tsx
> +export default async function AuthLayout({ children }: Props): Promise<JSX.Element> {
Got it

2024-03-04 07:17 UTC, pesickadavid commented on apps/app/src/app/(reset-password)/layout.tsx
> +export default function AuthLayout({ children }: Props): JSX.Element {
Got it

2024-03-04 08:02 UTC, pesickadavid commented on apps/app/src/app/(reset-password)/reset-password/new/layout.tsx
> +export default async function AuthLayout({ children }: Props): Promise<JSX.Element> {
Updated

2024-03-04 08:08 UTC, pesickadavid commented on apps/app/src/app/auth/confirm/route.ts
> +  redirectTo.pathname = "/error";
Well, this route should eventually replace the `/auth/callback` route, to finish the switch to the OTP auth

2024-03-04 08:08 UTC, pesickadavid commented on apps/app/src/app/(reset-password)/reset-password/new/layout.tsx
> +  const auth = await getAuth();
Moved it

2024-03-04 08:29 UTC, VojtechVidra commented on apps/app/src/app/auth/confirm/route.ts
> +  redirectTo.pathname = "/error";
That is true. However if the verification link, either for reset password or registration, is invalid then it redirects to the error page. Currently `/error` is default Next.js error page so we should atleast add some better information for the user about what happened. And if we can differentiate between reset password and registration link we could also provide action how to resolve this.

2024-03-05 10:24 UTC, VojtechVidra commented on apps/app/src/auth/server-actions.ts
> +    redirectTo: routes.resetPasswordNew,
This redirectTo might need absolute url as in `signUp` method

2024-03-05 10:26 UTC, VojtechVidra commented on apps/app/src/app/reset-password/new/reset-password-new-form.tsx
> +        <Input
Maybe we should add repeat password input, what do you think @OPesicka ?

2024-03-05 10:41 UTC, OPesicka commented on apps/app/src/app/reset-password/new/reset-password-new-form.tsx
> +        <Input
I'd skip it.. we don't have it in registration either (or in Atmos afaik)

2024-03-06 05:44 UTC, VojtechVidra commented on apps/app/public/gotrue/mailer/templates/account-recovery-template.html
> +{"transactionalId":"clpn08i4l056sl90ojahcq01m","email":"{{ .Email }}","dataVariables":{"flowsUrl":"{{ .SiteURL }}/auth/confirm?token_hash={{ .TokenHash }}&type=recovery&redirect_to={{ .SiteURL }}/res
I would remove `redirect_to` query parameter. We can do the same in app thanks to the `type` query parameter

2024-03-06 17:06 UTC, pesickadavid commented on apps/app/src/app/auth/confirm/route.ts
> +  redirectTo.pathname = "/error";
Yup, added a redirect to `verifyError` page with an error message

2024-03-06 17:14 UTC, pesickadavid commented on apps/app/src/auth/server-actions.ts
> +    redirectTo: routes.resetPasswordNew,
Apparently it's not needed at all, works fine without the redirectTo field. Maybe it's another Supabase brokey docs thing.

2024-03-06 17:18 UTC, pesickadavid commented on apps/app/public/gotrue/mailer/templates/account-recovery-template.html
> +{"transactionalId":"clpn08i4l056sl90ojahcq01m","email":"{{ .Email }}","dataVariables":{"flowsUrl":"{{ .SiteURL }}/auth/confirm?token_hash={{ .TokenHash }}&type=recovery&redirect_to={{ .SiteURL }}/res
Makes sense, I've removed it here, we already have it in `auth/confirm/route.ts`

2024-03-07 07:18 UTC, VojtechVidra commented
Please, resolve confilicts so we can merge it 🙂

2024-03-08 18:22 UTC, pesickadavid commented on apps/app/src/app/auth/confirm/route.ts
> +  redirectTo.pathname = routes.verifyError({
Updated it, so it's like the `callback` route

2024-03-08 18:23 UTC, pesickadavid commented on apps/app/src/app/reset-password/new/reset-password-new-form.tsx
> +          <Captcha action="resetPasswordNew" ref={captchaRef} />
True 😄, removed it.

2024-03-08 18:34 UTC, pesickadavid commented
> Please, resolve confilicts so we can merge it 🙂

Finished 🙂

2024-03-11 09:59 UTC, VojtechVidra approved these changes

2024-03-11 10:00 UTC, merged