Personal settings
RBND-studio/flows-cloud pull request #184
Opened 2024-03-12 21:01 UTC by pesickadavid

2024-03-16 17:16 UTC, pesickadavid commented
@OPesicka  personal settings are now funtionally working, please add some nicer UI

2024-03-30 12:19 UTC, VojtechVidra requested changes

2024-03-30 12:19 UTC, VojtechVidra commented on apps/app/src/app/(dashboard)/user/[userId]/settings/connected-account.tsx
> +                _disabled: {
I would prefer wrapping the button in div, instead of hacking its css 😄

2024-03-30 12:19 UTC, VojtechVidra commented on apps/app/src/app/(dashboard)/user/[userId]/settings/delete-account-dialog.tsx
> +    await new Promise((resolve) => setTimeout(resolve, 2000));
Are we keeping those waits?

2024-03-30 12:19 UTC, VojtechVidra commented on apps/backend/src/organizations/organizations.service.ts
> +  async leaveOrganization({
I think we can replace `leaveOrganization` with `removeUser`.

2024-03-30 12:19 UTC, VojtechVidra commented on apps/app/src/app/(dashboard)/user/[userId]/settings/connected-account.tsx
> +    onUnlink();
Let's check if send results returned `error` and don't call onUnlink if it did

2024-03-30 12:19 UTC, VojtechVidra commented on apps/app/src/app/(dashboard)/user/[userId]/settings/connected-accounts.tsx
> +    provider: "email",
Maybe we can use simpler interface so we don't have to define arbitrary `created_at`, `updated_at`, etc.

2024-04-01 06:42 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/connected-account.tsx
> +                _disabled: {
I always try to use css instead of div trees :D

2024-04-01 06:42 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/connected-account.tsx
> +    onUnlink();
Updated

2024-04-01 06:42 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/connected-account.tsx
> +      errorMessage: "Failed to unlink account",
Added

2024-04-01 06:43 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/connected-account.tsx
> +  const { send } = useSend();
Aah should've checked good to know

2024-04-01 06:48 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/connected-accounts.tsx
> +    provider: "email",
Seems not needed, but i've updated it

2024-04-01 06:50 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/connected-accounts.tsx
> +          ? [emailIdentity, ...(supabaseUser.identities ?? [])].map((identity) => (
Aaah, i've filtered it out now

2024-04-01 06:51 UTC, VojtechVidra commented on apps/app/src/app/(dashboard)/user/[userId]/settings/connected-account.tsx
> +                _disabled: {
I mean if we wrap the button in div we don't have to change its pointer-events

2024-04-01 07:02 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/connected-accounts.tsx
> +  const handleOnUnlink = async (): Promise<void> => {
Okayy, i've updated it to a server component

2024-04-01 07:04 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/delete-account-dialog.tsx
> +    await new Promise((resolve) => setTimeout(resolve, 2000));
We could, and in a few months we could do a pref update with a blog post "We've shaved 4s from a delete account action" and just remove them :D
jk, i've deleted them

2024-04-01 07:06 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/delete-account-dialog.tsx
> +  const [isLoading, setIsLoading] = useState(false);
We could, yes

2024-04-01 07:08 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/delete-account-dialog.tsx
> +          loading={isLoading}
Well, `isDisabled` is true in more occasions than only when fetching data. And I've wanted to show spiner when actually doing something.

2024-04-01 07:10 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/organization-leave-dialog.tsx
> +    router.refresh();
Nice func :O added it

2024-04-01 07:10 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/organization-leave-dialog.tsx
> +      toast.error(res.error.message);
Removed

2024-04-01 07:14 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/password-change-dialog.tsx
> +            ml: "auto",
Updated it

2024-04-01 07:20 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/password-change-dialog.tsx
> +            disabled={!formState.isDirty}
I dont think so. The disabled button clearly shows that the user have not enered anything. But i've removed it.

2024-04-01 07:23 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/password-change-dialog.tsx
> +              color: "text.danger!",
Added it

2024-04-01 07:24 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/password-change-dialog.tsx
> +    // eslint-disable-next-line @typescript-eslint/no-unsafe-call -- zodResolver is a function
Weird, it complained, but now its okay

2024-04-01 07:27 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/password-change-dialog.tsx
> +      password: "",
It is recomended by `react-hook-form`

2024-04-01 07:30 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/personal-settings-header.tsx
> +  const { auth } = useAuth();
The two return different data and we need the users name here

2024-04-01 07:31 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/layout.tsx
> +export function generateMetadata(): Metadata {
Yup

2024-04-01 07:33 UTC, pesickadavid commented on apps/app/src/lib/api/schema.d.ts
I've found this file, but not the cmd :D

2024-04-01 07:35 UTC, pesickadavid commented on apps/app/src/lib/validation-schemas.ts
> +export const SignUpFormSchema = z.object({
I'll do it in separate PR as we've talked

2024-04-01 07:41 UTC, pesickadavid commented on apps/backend/src/organizations/organizations.service.ts
>        .leftJoin(
It did, but was trully not needed once i've changed the subquery

2024-04-01 07:46 UTC, VojtechVidra commented on apps/app/src/app/(dashboard)/user/[userId]/settings/delete-account-dialog.tsx
> +          loading={isLoading}
Yes, that is correct, I'm just pointing out that `isLoading` and `loading` don't have to be part of `isDisabled`

2024-04-01 07:46 UTC, VojtechVidra commented on apps/app/src/app/(dashboard)/user/[userId]/settings/personal-settings-header.tsx
> +  const { auth } = useAuth();
Then we should return the same `Session` from `getAuth` as from `useAuth`. The data is there, it's just formatted differently 🙂

2024-04-01 07:49 UTC, VojtechVidra commented on apps/app/src/app/(dashboard)/user/[userId]/settings/password-change-dialog.tsx
> +      password: "",
Is it? I'm curious, I must have overlooked it 😄

2024-04-01 07:49 UTC, pesickadavid commented on apps/backend/src/organizations/organizations.service.ts
> +    const membersQuery = this.databaseService.db
It didn't have to be a subquery.

2024-04-01 07:51 UTC, VojtechVidra commented on apps/app/src/app/(dashboard)/user/[userId]/settings/password-change-dialog.tsx
> +            disabled={!formState.isDirty}
@OPesicka what's the best UX solution?
Context: Should a submit button be disabled when you open dialog because you haven't entered anything yet? 🤔

2024-04-01 07:55 UTC, pesickadavid commented on apps/backend/src/organizations/organizations.service.ts
> +  async leaveOrganization({
I dont think so, `leaveOrganization` is performed by the user itself and `removeUser` is done by somebody else. The two functions are different

2024-04-01 07:59 UTC, pesickadavid commented on apps/backend/src/users/users.service.ts
> +    const currentIdentity = await this.databaseService.db.execute(
Supabase allows you to log in with email/pass even if you dont have any identities, so it is not needed to check

2024-04-01 08:00 UTC, pesickadavid commented on apps/backend/src/users/users.service.ts
> +    //Delete users identities
What kind of checks?

2024-04-01 08:00 UTC, pesickadavid commented on apps/backend/src/users/users.service.ts
> +    if (usersResult.length === 0) throw new NotFoundException();
Probably :D

2024-04-01 08:02 UTC, pesickadavid commented on apps/backend/src/users/users.service.ts
> +          has_password: sql<boolean>`case when encrypted_password <> '' then true else false end as e`,
Force of habit from MSSQL :)

2024-04-01 11:29 UTC, VojtechVidra commented on apps/backend/src/users/users.service.ts
> +    const currentIdentity = await this.databaseService.db.execute(
I'm confused, does it mean the email identity doesn't have password defined? What happens when I have only email identity I delete it and I log out? Can I still log in with the same password? Or can I sign up and create new identity for the same old user without identities?

2024-04-01 11:30 UTC, VojtechVidra commented on apps/backend/src/users/users.service.ts
> +    //Delete users identities
I would atleast check if user is part of any organization.

2024-04-01 11:37 UTC, VojtechVidra commented on apps/backend/src/organizations/organizations.service.ts
> +  async leaveOrganization({
Think about it and also look at the functions, they do exactly the same thing. Except `removeUser` tells you to use `leaveOrganization` if you're trying to remove yourself.

2024-04-01 11:40 UTC, VojtechVidra commented on packages/ui/src/input/input.tsx
> +          color={error ? "danger" : "subtle"}
Let's use `undefined` instead of `subtle` please 🙂

2024-04-01 11:42 UTC, VojtechVidra commented on apps/backend/src/users/users.service.ts
> +      //   this.databaseService.db.query.users.findFirst({
Pls remove this commented out code 😄

2024-04-01 11:45 UTC, VojtechVidra commented on apps/backend/src/organizations/organizations.service.ts
> +        organizations.id,
I think just `.groupBy(organizations.id)` should do the trick, what do you think?

2024-04-05 11:34 UTC, pesickadavid commented on apps/backend/src/organizations/organizations.service.ts
> +        organizations.id,
Group by has to include all the non-aggregated columns, otherwise SQL complains.

2024-04-05 11:34 UTC, pesickadavid commented on apps/backend/src/organizations/organizations.service.ts
> +  async leaveOrganization({
I would leave it separated. When we introduce roles, `removeUser` is gonna have to check if `auth.userId` is authorized to remove users from org and I think it would be messy to also check if the `auth.userId === userId` . 
I know both functions have the same outcome, they have different meaning however.

2024-04-05 11:41 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/password-change-dialog.tsx
> +      password: "",
`The defaultValues prop populates the entire form with default values. It supports both synchronous and asynchronous assignment of default values. While you can set an input's default value using defaultValue or defaultChecked (as detailed in the official React documentation), it is recommended to use defaultValues for the entire form.`

(react-hook-form docs)[https://react-hook-form.com/docs/useform#defaultValues]

2024-04-05 12:06 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/personal-settings-header.tsx
> +  const { auth } = useAuth();
I've unified it. Now both use the same "mapper" function

2024-04-05 12:08 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/[userId]/settings/personal-settings-header.tsx
> +  const { auth } = useAuth();
And also this is now server comopnent

2024-04-05 12:14 UTC, pesickadavid commented on apps/backend/src/users/users.service.ts
> +    const currentIdentity = await this.databaseService.db.execute(
Well password is defined on the user seaparate from identities. So you have `user` with email and password, then sometimes supabase creates a `identity` of `email` type, but not always :D sooo you can have `user` with a password and 0 `idenities` and still be able to log in.

2024-04-05 12:23 UTC, pesickadavid commented on apps/backend/src/users/users.service.ts
> +    //Delete users identities
It's checked now

2024-04-06 07:04 UTC, VojtechVidra commented on apps/backend/src/users/users.service.ts
> +    const currentIdentity = await this.databaseService.db.execute(
But what if the user doesn't have a password and is trying to delete the last identitity. That could cause some problems, what do you think?

2024-04-06 07:06 UTC, VojtechVidra commented on apps/app/src/app/(dashboard)/user/[userId]/settings/password-change-dialog.tsx
> +      password: "",
Good to know, thanks 👍

2024-04-06 07:41 UTC, OPesicka commented on apps/app/src/app/(dashboard)/user/[userId]/settings/connected-account.tsx
> +              onClick={handleUnlink}
Yup pls

2024-04-06 09:24 UTC, VojtechVidra approved these changes

2024-04-06 11:05 UTC, merged