feat(app): flow editor autosave
RBND-studio/flows-cloud pull request #335
Opened 2024-05-16 09:31 UTC by VojtechVidra

2024-05-18 12:13 UTC, OPesicka requested changes

2024-05-18 12:13 UTC, OPesicka commented on apps/app/src/app/(dashboard)/org/[organizationId]/project/[projectId]/flow/[flowId]/edit/flow-edit-form.tsx
>                <Button variant="ghost" size="icon" asChild>
What about disabling the close until the changes are saved? Or having some general "You have unsaved changes" dialog?

2024-05-19 06:46 UTC, OPesicka commented on apps/app/src/app/(dashboard)/org/[organizationId]/project/[projectId]/flow/[flowId]/edit/remove-draft.tsx
> +        {/* TODO: make this close on click */}
@VojtechVidra I couldn't figure this out 😄

2024-05-19 11:30 UTC, VojtechVidra commented on apps/app/src/app/(dashboard)/org/[organizationId]/project/[projectId]/flow/[flowId]/edit/flow-edit-form.tsx
>                <Button variant="ghost" size="icon" asChild>
I've added two changes:
- the page will prompt you beforeunload (refresh or close) and save so you can actually cmd + w, esc, cmd + w
- the form will save in the background if you navigate to other page within app

2024-05-19 11:31 UTC, VojtechVidra commented on apps/app/src/app/(dashboard)/org/[organizationId]/project/[projectId]/flow/[flowId]/edit/remove-draft.tsx
> +        {/* TODO: make this close on click */}
Fixed 👍 😄

2024-05-19 11:55 UTC, OPesicka commented on apps/app/src/app/(dashboard)/org/[organizationId]/project/[projectId]/flow/[flowId]/edit/flow-edit-form.tsx
>                <Button variant="ghost" size="icon" asChild>
Nice!

2024-05-19 12:19 UTC, merged