feat(app): unlink account dialog
RBND-studio/flows-cloud pull request #339
Opened 2024-05-18 14:51 UTC by pesickadavid

closes #315

2024-05-19 06:24 UTC, VojtechVidra commented on apps/app/src/app/(dashboard)/user/settings/connected-account.tsx
> +  const [confirmDialogOpen, setConfirmDialogOpen] = useState(false);
In this case we don't have to control dialog state since it gets closed automatically because this components gets removed.

2024-06-01 16:35 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/settings/connected-account.tsx
> +  const [confirmDialogOpen, setConfirmDialogOpen] = useState(false);
🤯 true

2024-06-04 07:42 UTC, VojtechVidra requested changes

2024-06-07 13:45 UTC, pesickadavid commented on apps/app/src/app/(dashboard)/user/settings/connected-account.tsx
> +    if (!error) {
That is hella confusing 😄 but i get the point

2024-06-07 14:27 UTC, VojtechVidra approved these changes

2024-06-07 14:29 UTC, merged