feat(be): delete progress endpoints
RBND-studio/flows-cloud pull request #442
Opened 2024-07-10 12:23 UTC by VojtechVidra

2024-07-10 14:53 UTC, VojtechVidra commented on apps/backend/src/sdk/sdk.service.ts
> +            this.databaseService.db
@pesickadavid please check the new table and newly added queries if its looks good.

2024-07-10 14:53 UTC, VojtechVidra commented on packages/db/drizzle/migrations/0036_zippy_wallflower.sql
It would be great if we could somehow migrate current user progress (`cancelFlow` or `finishFlow` event) to this new table. Can you please take care of it? @pesickadavid

2024-07-13 08:52 UTC, pesickadavid commented on apps/backend/src/sdk/sdk.service.ts
> +    const flowIds = await this.databaseService.db.query.flows.findMany({
This could probably be just one db query  i.e. 
```sql
IF EXISTS (SELECT * FROM flows WHERE ...) THEN
	INSERT INTO ...
END IF;
```
but it depends on whether this is needed 😄

2024-07-13 08:53 UTC, pesickadavid commented on apps/backend/src/sdk/sdk.service.ts
> +    const flowIds = await this.databaseService.db.query.flows.findMany({
This is what I mean on [StackOverflow](https://stackoverflow.com/a/11299968/12928571)

2024-07-13 08:56 UTC, pesickadavid commented on apps/backend/src/projects/projects.service.ts
> +      return this.databaseService.db.query.flows
Probably could be the same function as in `sdk.service:347`?

2024-07-13 08:59 UTC, pesickadavid requested changes
Other than the maybe `deleteUserProgress` duplication, everything looks good!

2024-07-13 17:45 UTC, pesickadavid commented on packages/db/drizzle/migrations/0036_zippy_wallflower.sql
I've added a drizzle migration that will push the user progress to this new table.
It's just a simple SQL query.

2024-07-14 06:25 UTC, VojtechVidra commented on packages/db/drizzle/migrations/0036_zippy_wallflower.sql
Looks good!

2024-07-14 06:26 UTC, VojtechVidra commented on apps/backend/src/sdk/sdk.service.ts
> +    const flowIds = await this.databaseService.db.query.flows.findMany({
If there's an elegant way of writing that in drizzle, you can try to do that 😄

2024-07-14 07:02 UTC, VojtechVidra commented on apps/backend/src/projects/projects.service.ts
> +      return this.databaseService.db.query.flows
It looks similar, but this method is using `flow.id` and the one in `sdk.service` is using `flow.human_id`. I would leave it separate for now,

2024-07-14 09:05 UTC, pesickadavid commented on apps/backend/src/sdk/sdk.service.ts
> +    const flowIds = await this.databaseService.db.query.flows.findMany({
Elegant? No 😄 
Way? Yes

2024-07-14 09:05 UTC, pesickadavid commented on apps/backend/src/projects/projects.service.ts
> +      return this.databaseService.db.query.flows
Aye

2024-07-24 05:58 UTC, OPesicka approved these changes

2024-07-24 10:30 UTC, merged